### ISSUE TITLE
Hello I am new to javascript and want to setup this project locally

### ISSUE THREAD

**Issue by M-MohitSharma** [mani-barathi/Octave#1]
its giving some firebase errors .
can you please suggest what to do ?

![12](https://user-images.githubusercontent.com/41113326/116696847-0b29f680-a9e0-11eb-818a-ff60fe218b02.PNG)

**Comment by mani-barathi** [comment]
@M-MohitSharma 

- Replace your keys
- Make sure you have enabled email-password login and google login in firebase console

``` javascript
import firebase from "firebase/app";
import "firebase/auth";
import "firebase/firestore";
import "firebase/storage";

// Replace project keys here
const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: "",
};

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

export const db = firebase.firestore();
export const storage = firebase.storage();
export const auth = firebase.auth();
export const provider = new firebase.auth.GoogleAuthProvider();

```

May be I'll add a firebase.example.js a a reference

**Comment by M-MohitSharma** [comment]
@mani-barathi it worked the app is compiled. 
one more thing. Can you tell me why the admin option is not available to upload songs. 
I have enabled email and google login. 
there are a lot of errors in console.

**Comment by mani-barathi** [comment]
@M-MohitSharma 
I just removed the admin page from the navbar drop down as some people are spamming it by upload songs. But you can access it by typing `/admin` in the browser URL box

**Comment by M-MohitSharma** [comment]
@mani-barathi  
I am not able to fetch the uploaded songs from firebase.
I think I need to make some specific firestore or storage components. 
can you please guide me through that.

**Comment by mani-barathi** [comment]
@M-MohitSharma 
did you create Indexes in the firebase, if not then check [Note Section in the README](https://github.com/mani-barathi/Octave#note)

**Comment by M-MohitSharma** [comment]
@mani-barathi 
like this 
![13](https://user-images.githubusercontent.com/41113326/116718404-8cd94e80-a9f7-11eb-9e0b-45ab2b946ca4.PNG)

**Comment by mani-barathi** [comment]
I Guess that's due the firestore security rules, try replacing this in your firestore rules in firebase console

``` js
service cloud.firestore {
  match /databases/{database}/documents {
  
     match /{document=**}{
    	allow read,write: if request.auth != null;
     }
   
   	 match /favourites/{docId}{
       allow create: if request.auth.uid == request.resource.data.uid;
       allow read,update,delete : if request.auth.uid == resource.data.uid;
    }
   
   }
}
```

**Comment by mani-barathi** [comment]
@M-MohitSharma 
Not sure. I just added the loading spinner like a few days before.
